### ISSUE TITLE
Crash on server

### ISSUE THREAD

**Issue by anviaan** [gizmo-ds/i-have-slept-mod#1]
I downloaded the mod in version 1.1.0+mc1.21 and the server crashes, I attach the error of the crash and the list of Mods that are on the server:

Mods List
```
- advancedbackups 3.6.3
- carpet 1.4.147+v240613
- chiseled-bookshelf-visualizer 3.3
- collective 7.87
- configurabledespawntimer 4.2
- fabric-api 0.105.0+1.21.1
- fabric-essentials 1.2.1+1.21.1
- fabrictailor 2.5.0
- owo 0.12.15+1.21
- servercore 1.5.5+1.21.1
- shulkerboxtooltip 5.1.1+1.21.1
- spark 1.10.109
```
Log of the crash
```
Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'i_have_slept' at 'dev.aika.i_have_slept.fabric.IHaveSleptFabric'!
        at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403) ~[fabric-loader-0.16.7.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.16.7.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401) ~[fabric-loader-0.16.7.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.16.7.jar:?]
        at knot/net.minecraft.server.Main.main(Main.java:111) [server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.7.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.7.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.7.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.7.jar:?]
Caused by: java.lang.IllegalAccessError: class dev.aika.i_have_slept.IHaveSlept tried to access method 'net.minecraft.class_1928$class_4314 net.minecraft.class_1928$class_4310.method_20759(boolean)' (dev.aika.i_have_slept.IHaveSlept and net.minecraft.class_1928$class_4310 are in unnamed module of loader 'knot' @18be83e4)
        at knot/dev.aika.i_have_slept.IHaveSlept.<clinit>(IHaveSlept.java:12) ~[i_have_slept-fabric-1.1.0+mc1.21.1.jar:?]
        at knot/dev.aika.i_have_slept.fabric.IHaveSleptFabric.onInitialize(IHaveSleptFabric.java:14) ~[i_have_slept-fabric-1.1.0+mc1.21.1.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.7.jar:?]
        ... 6 more
```

**Comment by gizmo-ds** [comment]
Thank you for reporting the issue. I’ve made some changes to address it, and I’ve just released a new version. Could you please try the latest release and let me know if the issue is resolved?

https://github.com/gizmo-ds/i-have-slept-mod/releases/tag/v1.1.1%2Bmc1.21

**Comment by gizmo-ds** [comment]
Please note that the latest version requires Fabric API as a dependency.

**Comment by anviaan** [comment]
It appears to be working as it should
